// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4BfUDOtjV5hJHpfaxyRjIVsyPl-NdLp8',
    appId: '1:845074066861:web:0d933edc15903ca0064524',
    messagingSenderId: '845074066861',
    projectId: 'gastos-c4a01',
    authDomain: 'gastos-c4a01.firebaseapp.com',
    storageBucket: 'gastos-c4a01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrZ_2Hz8lSCip95BQRLxf_ye2iBD_Unj8',
    appId: '1:845074066861:android:b779f3cb32d18b9e064524',
    messagingSenderId: '845074066861',
    projectId: 'gastos-c4a01',
    storageBucket: 'gastos-c4a01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbBqkLmZbsoXs75OqqcOxjgISPp00g-Jo',
    appId: '1:845074066861:ios:5feb4cf35142e826064524',
    messagingSenderId: '845074066861',
    projectId: 'gastos-c4a01',
    storageBucket: 'gastos-c4a01.firebasestorage.app',
    iosBundleId: 'com.example.gastos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbBqkLmZbsoXs75OqqcOxjgISPp00g-Jo',
    appId: '1:845074066861:ios:5feb4cf35142e826064524',
    messagingSenderId: '845074066861',
    projectId: 'gastos-c4a01',
    storageBucket: 'gastos-c4a01.firebasestorage.app',
    iosBundleId: 'com.example.gastos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4BfUDOtjV5hJHpfaxyRjIVsyPl-NdLp8',
    appId: '1:845074066861:web:38e19a2f5ad30730064524',
    messagingSenderId: '845074066861',
    projectId: 'gastos-c4a01',
    authDomain: 'gastos-c4a01.firebaseapp.com',
    storageBucket: 'gastos-c4a01.firebasestorage.app',
  );
}
